### PR TITLE
Fix for Issue #18

### PR DESCRIPTION
**Pull request by pixeldock**
This PR fixes that all displayed clustered annotations were always removed and re-added when the mapView's region changed.

I added a custom `hash` for the `FBAnnotationCluster` class and overrode the `isEqual:` method so that two objects are considered equal when their `coordinates` are equal. (I took the cue from the `TBAnnotationClustering` example project.)

This enables the `FBClusteringManager` to keep annotations that did not change their coordinates and only removes annotations that are not on the map anymore.

This fixes the behavior described in issue https://github.com/infinum/FBAnnotationClustering/issues/18

### CODE REVIEW

**Comment by Kiirojin** [comment]
I can confirm this fixes the behavior.

**Comment by filipbec** [comment]
Hi @pixeldock. Since your `isEqual` method relies on the `hash` method, it's not completely correct. 
You can find a safer solution here: https://github.com/infinum/FBAnnotationClustering/issues/2#issuecomment-56293567

**Comment by sirnacnud** [comment]
I went ahead an implemented isEqual as suggested, see #25.

**Comment by paulthorsteinson** [comment]
Currently this change can lead to a crash.  I believe the situation to recreate is to add 2 annotations with the same coordinate - do a remove of all the annotations and then add those annotations back.  This is because the count will get out of sync on the removal causing an index out of bounds when it goes to add them back in [FBQuadTree.m](https://github.com/infinum/FBAnnotationClustering/blob/master/FBAnnotationClustering/FBQuadTree.m):
```
   if ([node.annotations containsObject:annotation]) {
        [node.annotations removeObject:annotation];
        node.count--;
        return YES;
    }
```
Because removeObject uses isEqual - it removes the annotations that are equal - in the case of annotations with the same lat/long it will then remove them all but it only decrements count by 1.  Spitballing a few solutions:  1)  Remove the count property on a FBQuadTreeNode and in its place use node.annotations.count.  I found it weird that it had its own count property that could get out of sync in the first place.  My assumption is that using that increased performance.  2) In the case that the count property was for performance then instead of ```node.count--;``` you could put ```node.count = node.annotations.count;``` in place of that so even if the isequals caused the deletion of more than one you will still have the proper count.

**Comment by Dundo7** [comment]
Hi, FBAnnotationClustering is no longer maintained.

**Pull request closed without merging**
